### ISSUE TITLE
install

### ISSUE THREAD

**Issue by brunofisico** [dfm/CeleriteFlow#1]

**Comment by dfm** [comment]
This should install using the standard `python setup.py install`, but the interface isn't very stable (hence the lack of docs) so use at your own risk!

**Comment by brunofisico** [comment]
Thanks dfm...I tried use this but the error was stranger...
like this:


**/home/bruno/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    import celeriteflow  # NOQA
  File "/home/bruno/CeleriteFlow-master/celeriteflow/__init__.py", line 8, in <module>
    from .celeriteflow import CeleriteFlowMatrix
  File "/home/bruno/CeleriteFlow-master/celeriteflow/celeriteflow.py", line 8, in <module>
    from .ops import to_dense, get_matrices, factor, solve, matmul
  File "/home/bruno/CeleriteFlow-master/celeriteflow/ops/__init__.py", line 14, in <module>
    mod = tf.load_op_library(os.path.join(dirname, "celerite_op" + suffix))
  File "/home/bruno/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/bruno/CeleriteFlow-master/celeriteflow/ops/celerite_op.cpython-36m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory**

**Comment by dfm** [comment]
I pushed a change that might fix this for you!

**Comment by brunofisico** [comment]
Thank again dfm, but are you right about this:

gcc -pthread -B /home/bruno/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bruno/anaconda3/include/python3.6m -c celeriteflow/ops/celerite_factor_op.cc -o build/temp.linux-x86_64-3.6/celeriteflow/ops/celerite_factor_op.o -I/home/bruno/anaconda3/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -stdlib=libc++ -O2 -undefined dynamic_lookup
**gcc.exec: error: unrecognized command line option '-stdlib=libc++'**
error: command 'gcc' failed with exit status 1

**Comment by dfm** [comment]
For your specific problem, you'll need to edit the setup.py file yourself. I'm not going to support multiple compilers yet!
